### ISSUE TITLE
Could you please share the datasets?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [AlexMa011/pytorch-polygon-rnn#1]
It is exciting to read this beautiful code. So I star it immediately. However I do not understand how to find and feed the data with polygon from the website. In other words, there are no json files with good format I've found. 
so could you please share the datasets, so that we can train and test with this code more easily? thanks for your kindness work!

**Comment by AlexMa011** [comment]
Glad that you starred this project. I think I claimed it in README file that you can download cityscape dataset(gtFine_trainvaltest.zip (241MB) and leftImg8bit_trainvaltest.zip (11GB)) first. And use the generate_data script to generate the dataset for training.

**Comment by yuqing-liu-dut** [comment]
Thanks for your reply. There is another problem while reading your code. There is another build-in lstm layer used for training and testing, which is not mentioned in the paper. Could you please talk about the use of this layer?

**Comment by AlexMa011** [comment]
I use the fully connected layer and the lstm layer mainly because the output is d*d+1 dimension. Since the source code is not released, I do not know the exact implementation. But the fc layers do help the training process.

**Comment by AlexMa011** [comment]
If there is no problem with the dataset, I will close the issue.
