### ISSUE TITLE
Training is throwing error.

### ISSUE THREAD

**Issue by vineetjai** [AlexMa011/pytorch-polygon-rnn#11]
I am getting error while doing training. Please help me:
```
$ python train.py --gpu_id 0 --batch_size 8  --lr 0.0001
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from test import test
  File "/home/ai/Documents/vineet/pytorch-polygon-rnn/test.py", line 14, in <module>
    from utils.utils import img2tensor
ImportError: No module named 'utils.utils'
```
I think there has to be file(`utils.py`) in utils folder which consist of img2tensor, iou  and getbboxfromkps. So please include function in utils folder or change `test.py` such that
```
from utils.utils import img2tensor
from utils.utils import iou, getbboxfromkps
```  
can be replaced by other function.
Or am I need to install packages other than requirements package?
please correct me if I am wrong.

**Comment by AlexMa011** [comment]
Sorry about that. I will try to update to fix the error as. It was my mistake to forget to add the utils file.

**Comment by AlexMa011** [comment]
I already update the project, please try it again.

**Comment by vineetjai** [comment]
Also can you share your pretrained model?

**Comment by vineetjai** [comment]
As `python train.py --gpu_id 0 --batch_size 8  --lr 0.0001 ` is throwing error `FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/train1_20.pth'`. So please upload your pretrained model also.
