### ISSUE TITLE
Differences to Original Polygon RNN Paper

### ISSUE THREAD

**Issue by MSiam** [AlexMa011/pytorch-polygon-rnn#3]
Hi,

  Thanks for the re-implementation you provided. I had two questions regarding your code:
1- How are you estimating the first vertex for the polygon in your code? 
2- Why do you have the LSTM layer after the two-layer ConvLSTM? Is this following the method in the paper or for what reason?
thx

**Comment by AlexMa011** [comment]
1. I use two virtual starting vertex as in image captioning, and the first vertex is trained and tested with the same virtual vertices.
2. The LSTM is added to satisfy the D*D+1 dimension as in the paper. Since the source code is not released, I assume there is a LSTM or fc layer after the ConvLSTM

**Comment by MSiam** [comment]
Aha I see, thanks for your reply.
