### ISSUE TITLE
Running Correction code 

### ISSUE THREAD

**Issue by yshvrdhn** [AlexMa011/pytorch-polygon-rnn#6]
Is it possible to run the correction method using this code as described in the paper? Essentially I want to feed in the corrected polygon to generate new predictions using that?

**Comment by AlexMa011** [comment]
Since at every time step, the model needs the first vertex and previous two vertices, you can easily change the previous vertices to corrected ones.

**Comment by AlexMa011** [comment]
I will close it if you don't have further problems.

**Comment by yshvrdhn** [comment]
Sure. Thank you.
